FROM openjdk:17-alpine
MAINTAINER oleksandr.zhytariuk (roofeeoff@gmail.com)
COPY target/quiz-service-0.0.1-SNAPSHOT.jar quiz-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/quiz-service-0.0.1-SNAPSHOT.jar"]