server:
  port: 8080

spring:
  application:
    name: quiz-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 3026606117
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
